# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpenLDM
                                 A QGIS plugin
 Python based Plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-21
        copyright            : (C) 2026 by Indian Institute of Remote Sensing
        email                : jha.ashutosh@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OpenLDM class from file OpenLDM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .OpenLDMgui import OpenLDM
    return OpenLDM(iface)
