# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpenLDM
                                 A QGIS plugin
 Python based Plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-21
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Indian Institute of Remote Sensing
        email                : jha.ashutosh@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import importlib
import os
import os.path
import sys

from qgis.PyQt.QtCore import QEventLoop, QLocale, Qt, QThread, QTranslator, QCoreApplication, pyqtSignal
from qgis.core import QgsApplication, QgsSettings
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox, QProgressDialog

from . import dependency_check

# The exact files GDAL/PROJ themselves complain about being unable to
# find (confirmed for real: "Cannot find gdalvrt.xsd (GDAL_DATA is not
# defined)" / "Cannot find proj.db") -- checking for these specifically,
# rather than just assuming a directory exists, is what makes
# _find_data_dir a real verification instead of a guess.
_GDAL_DATA_MARKER = "gdalvrt.xsd"
_PROJ_DATA_MARKER = "proj.db"


def _find_data_dir(search_root: str, marker_filename: str, max_depth: int = 6):
    """Searches under search_root for a directory containing
    marker_filename, breadth-first, bounded to max_depth levels so this
    can't turn into an unbounded scan of a large install tree. Returns
    the directory path, or None if nothing was found within the depth
    limit."""
    if not search_root or not os.path.isdir(search_root):
        return None
    current_level = [search_root]
    for _ in range(max_depth):
        next_level = []
        for d in current_level:
            try:
                entries = os.listdir(d)
            except OSError:
                continue
            if marker_filename in entries:
                return d
            for name in entries:
                sub = os.path.join(d, name)
                if os.path.isdir(sub) and not os.path.islink(sub):
                    next_level.append(sub)
        if not next_level:
            break
        current_level = next_level
    return None


def _ensure_gdal_proj_env():
    """QGIS configures its own bundled GDAL/PROJ internally (C++ API
    calls, e.g. CPLSetConfigOption) rather than through OS environment
    variables -- confirmed for real: GDAL_DATA/PROJ_LIB/PROJ_DATA are all
    unset in os.environ inside a running QGIS session, even though QGIS's
    own map canvas renders CRS-aware layers just fine. A *separate*
    Python-level import of rasterio/osgeo.gdal does its own GDAL/PROJ
    initialization using the standard env-var-based discovery, and
    without these set, it can't find its data files even though they
    exist on disk right next to QGIS's own copy -- confirmed for real:
    `proj_get_authorities_from_database: Cannot find proj.db` at import
    time, which breaks any CRS-dependent operation (reprojection, EPSG
    lookups) `LULC`'s rasterio-based I/O relies on throughout.

    Actually searches for the data directories rather than assuming a
    fixed layout: QgsApplication.pkgDataPath()/{gdal,proj} is tried
    first (confirmed correct on macOS, and QGIS's own documented,
    portable "qgis" resource-directory convention), verified by checking
    for the exact marker file GDAL/PROJ themselves look for -- if that
    doesn't check out (a different QGIS packaging layout on some
    platform/version), falls back to actually walking the install tree
    from QgsApplication.prefixPath() to find it, rather than silently
    setting a directory that might not really hold the data at all."""
    pkg_data = QgsApplication.pkgDataPath()
    prefix = QgsApplication.prefixPath()

    gdal_data = os.path.join(pkg_data, "gdal")
    if not os.path.isfile(os.path.join(gdal_data, _GDAL_DATA_MARKER)):
        gdal_data = _find_data_dir(prefix, _GDAL_DATA_MARKER)
    if gdal_data:
        os.environ.setdefault("GDAL_DATA", gdal_data)

    proj_data = os.path.join(pkg_data, "proj")
    if not os.path.isfile(os.path.join(proj_data, _PROJ_DATA_MARKER)):
        proj_data = _find_data_dir(prefix, _PROJ_DATA_MARKER)
    if proj_data:
        os.environ.setdefault("PROJ_LIB", proj_data)  # PROJ < 9
        os.environ.setdefault("PROJ_DATA", proj_data)  # PROJ >= 9


class _InstallWorker(QThread):
    """Runs dependency_check.install_missing() off the GUI thread, live-
    streaming pip's output back via a signal (queued automatically across
    threads by Qt, same pattern as gui/workers.py's BackgroundTaskWorker)."""

    output = pyqtSignal(str)
    finished_result = pyqtSignal(bool, str)

    def __init__(self, pip_names, venv_dir, parent=None):
        super().__init__(parent)
        self._pip_names = pip_names
        self._venv_dir = venv_dir

    def run(self):
        success, output = dependency_check.install_missing(
            self._pip_names, self._venv_dir, on_output=self.output.emit
        )
        self.finished_result.emit(success, output)


class OpenLDM:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Must happen before anything below can transitively import
        # rasterio/osgeo.gdal (dependency_check.missing_packages() does
        # exactly that, from the very first run() click) -- see
        # _ensure_gdal_proj_env's docstring for why this is needed at all.
        _ensure_gdal_proj_env()
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&OpenLDM')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

        # The real desktop GUI window (gui.main_window.LULCMainWindow),
        # created lazily on first run() and reused after that.
        self._window = None
        # Set True once missing_packages() comes back empty (or a manual
        # install fixes it) -- avoids re-checking on every click.
        self._deps_ok = False
        # Missing runtime dependencies are installed into a real venv
        # inside the plugin folder (built from QGIS's own bundled Python)
        # rather than into QGIS's own Python or the user's global
        # site-packages: self-contained, doesn't touch anything outside
        # this plugin folder, trivial to clean up (delete the plugin),
        # and sidesteps write-permission issues into a possibly
        # admin-owned QGIS install. If a previous session already built
        # it, pick its site-packages up immediately -- no need to wait
        # for _ensure_dependencies() to run again.
        self._venv_dir = os.path.join(self.plugin_dir, "venv")
        self._add_venv_to_syspath()

    def _add_venv_to_syspath(self):
        """Adds the plugin-local venv's site-packages to sys.path if the
        venv exists and isn't already on it. A venv only changes what a
        *newly launched* interpreter would see by default (its pyvenv.cfg)
        -- it does nothing for an already-running interpreter like this
        one, so the running QGIS process has to be told explicitly.

        Appended, not inserted at the front: `pip install --target`
        doesn't consult QGIS's own already-installed packages when
        resolving dependencies, so it can (and, confirmed for real,
        does -- installing statsmodels pulled in its own fresh numpy/
        scipy/pandas) end up with its own copies of things QGIS already
        has. Putting the venv first would let those freshly pip-installed
        copies shadow QGIS's own -- which broke rasterio/geopandas/
        sklearn/matplotlib outright, since they're compiled against
        QGIS's bundled numpy, not pip's newly fetched one. Appending
        means QGIS's own already-working packages are always found
        first; the venv only fills in what's genuinely missing."""
        if not os.path.exists(dependency_check.venv_python(self._venv_dir)):
            return
        site_packages = dependency_check.venv_site_packages(self._venv_dir)
        if site_packages not in sys.path:
            sys.path.append(site_packages)

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('OpenLDM', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'OpenLDM LULC Modeling'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&OpenLDM'),
                action)
            self.iface.removeToolBarIcon(action)
        if self._window is not None:
            self._window.close()
            self._window = None


    def _ensure_dependencies(self):
        """True if OpenLDM's runtime dependencies are importable (installing
        them first, with the user's consent, if not). False means the
        caller should abort -- either the user declined, or an automatic
        install failed and manual instructions were shown instead."""
        missing = dependency_check.missing_packages()
        if not missing:
            return True

        pip_names = [pip_name for _, pip_name in missing]
        reply = QMessageBox.question(
            self.iface.mainWindow(),
            "OpenLDM: missing dependencies",
            "OpenLDM needs the following Python packages, not currently "
            "installed in QGIS's own Python environment:\n\n"
            + ", ".join(pip_names)
            + "\n\nInstall them now? This needs internet access and may "
            "take a few minutes for the geospatial/scikit-learn stack.",
            QMessageBox.Yes, QMessageBox.No,
        )
        if reply != QMessageBox.Yes:
            return False

        progress = QProgressDialog(
            "Installing OpenLDM dependencies...", None, 0, 0, self.iface.mainWindow()
        )
        progress.setWindowModality(Qt.WindowModal)
        progress.setMinimumDuration(0)
        progress.setWindowTitle("OpenLDM")

        outcome = {}
        worker = _InstallWorker(pip_names, self._venv_dir, parent=self.iface.mainWindow())
        loop = QEventLoop()

        def _on_output(line):
            progress.setLabelText("Installing OpenLDM dependencies...\n" + line.strip()[-200:])

        def _on_finished(success, output):
            outcome["success"] = success
            outcome["output"] = output
            loop.quit()

        worker.output.connect(_on_output)
        worker.finished_result.connect(_on_finished)
        worker.start()
        progress.show()
        loop.exec_()
        progress.close()

        # Packages just landed in the venv's site-packages dir, so this
        # already-running interpreter has no reason to see them yet --
        # add that dir to sys.path before re-checking. Then always
        # re-verify by actually trying the imports rather than trusting
        # pip's exit code alone (caught for real during earlier `--user`
        # testing: pip reported success but the package stayed
        # unimportable in the already-running process regardless).
        self._add_venv_to_syspath()
        importlib.invalidate_caches()
        still_missing = dependency_check.missing_packages()
        if not still_missing:
            return True

        if outcome.get("success"):
            QMessageBox.information(
                self.iface.mainWindow(),
                "OpenLDM: restart required",
                "The required packages were installed, but this QGIS "
                "session can't pick them up until it's restarted.\n\n"
                "Please restart QGIS and try again.",
            )
            return False

        # Install genuinely failed -- fall back to manual instructions
        # using the exact interpreter QGIS is running.
        cmd = dependency_check.manual_install_command(
            [pip_name for _, pip_name in still_missing], self._venv_dir
        )
        tail = outcome.get("output", "")[-2000:]
        QMessageBox.critical(
            self.iface.mainWindow(),
            "OpenLDM: dependency install failed",
            "Could not install the required packages automatically.\n\n"
            "Please install them manually, e.g. from a terminal:\n\n"
            + cmd
            + "\n\nInstall log (tail):\n"
            + tail,
        )
        return False

    def run(self):
        """Ensures dependencies are present, then shows the real OpenLDM
        desktop GUI (gui.main_window.LULCMainWindow) as a window inside
        QGIS -- the same window `python OpenLDM.py` opens standalone,
        reusing QGIS's own already-running QApplication rather than
        creating a second one."""
        if not self._deps_ok:
            if not self._ensure_dependencies():
                return
            self._deps_ok = True

        if self._window is None:
            vendor_dir = os.path.join(self.plugin_dir, "vendor")
            if vendor_dir not in sys.path:
                sys.path.insert(0, vendor_dir)
            from gui.main_window import LULCMainWindow

            self._window = LULCMainWindow(embedded=True)
            self._window.setWindowIcon(QIcon(":/images/images/icon.png"))

        self._window.show()
        self._window.raise_()
        self._window.activateWindow()
